### ISSUE TITLE
[Incompatibility: Fabric]: Sounds

### ISSUE THREAD

**Issue by koffiato** [Tuinity/Moonrise#78] opened 2024-11-27 11:40 UTC
### Minecraft Version

1.21.3

### Moonrise Version

0.2.0-beta.4+e7510ed

### Mod Loader

Fabric

### Logs and Crash Reports

Link to log: https://mclo.gs/tkb6Xfj

### Additional Context

MRU version (Sounds dependency): 1.0.4
Sounds version: 2.2.1

**Comment by jpenilla** [comment] 2024-11-27 18:21
I don't see 'Sounds' or 'MRU' in that log, or any errors related to Moonrise

**Comment by koffiato** [comment] 2024-11-27 19:23
> I don't see 'Sounds' or 'MRU' in that log, or any errors related to Moonrise

Here's an instance of Fabric API, MRU, Moonrise and Sounds: https://mclo.gs/Ae5NlK3
Same instance with only Moonrise disabled: https://mclo.gs/iHWLdZk
Same instance wiith only Sounds disabled: https://mclo.gs/auVcvF2


Maybe it's a wonky interaction between the mods? Since both mods seem to work fine if not installed together.

**Comment by jpenilla** [comment] 2024-11-27 19:26
This is a dupe of #62, Sounds uses arch api

**Closed as not planned by jpenilla** 2024-11-27 19:26 UTC
Labels: duplicate, mod-incompatibility

**Comment by koffiato** [comment] 2024-11-27 19:30
This means Sounds/MRU uses bundled Architectury API, right? Just clarifying.

**Comment by jpenilla** [comment] 2024-11-27 19:38
Yes
![image](https://github.com/user-attachments/assets/6d8e7dc9-7181-4593-8fa9-4736eaa2217a)
