### ISSUE TITLE
[Incompatibility: <Fabric]>]: Architectury

### ISSUE THREAD

**Issue by carterlasalle** [Tuinity/Moonrise#86] opened 2024-12-27 08:14 UTC
### Minecraft Version

1.21.4

### Moonrise Version

0.2.0-beta.7+6ec14ff

### Mod Loader

Fabric

### Logs and Crash Reports

https://mclo.gs/gaTTfUN

### Additional Context

Architectury’s mixin in MixinChunkMap conflicts with Moonrise’s chunk_system.ChunkMapMixin injection. Both mods attempt to inject into the same method (method_17228 / net.minecraft.class_3898::save) at the same priority. This causes a crash when creating or loading worlds. The conflict can be resolved by disabling Moonrise’s chunk system or removing one of the conflicting mods.

**Comment by jpenilla** [comment] 2024-12-27 19:32
Duplicate of #62

**Closed as not planned by jpenilla** 2024-12-27 19:32 UTC
Labels: mod-incompatibility, needs-triage
